# Generated by Django 4.1.1 on 2022-12-01 11:21

from django.db import migrations, models
import superclient.setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_dhcpserverconfig_network_hotspotconfig_lanconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcpserverconfig',
            name='interface',
            field=models.CharField(max_length=16, unique=True, validators=[superclient.setting.models.DhcpServerConfig_validate_interface]),
        ),
        migrations.AlterField(
            model_name='network',
            name='interface',
            field=models.CharField(max_length=16, unique=True, validators=[superclient.setting.models.Network_validate_interface]),
        ),
    ]
